# Generated by Django 5.2.4 on 2025-07-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(choices=[('TAB', 'Tablet'), ('CAP', 'Capsule'), ('SYR', 'Syrup'), ('SUPP', 'Suppository'), ('VIAL', 'vial'), ('AMP', 'Ampoule'), ('OTHER', 'Other')], max_length=5)),
                ('fractions', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('expiry_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.medicine')),
            ],
        ),
    ]
